name: .github/workflows/readme_update.yml

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "*/30 * * * *"   # every 30 mins

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🍽️ Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: 🐍 Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: 💿 Install Jinja2 & requests
        run: pip install Jinja2 requests
      - name: 🍳 Update README
        run: |
          cd ${GITHUB_WORKSPACE}/profile/src/
          python update.py
      - name: 🚀 Deploy
        run: |
          git config user.name "Delfi-C3"
          git config user.email "Delfi-C3@users.noreply.github.com"
          git add .
          git commit -am "feat(auto generate): Updated content"
          git push --all -f https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
