
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      envPAT:
        required: true


jobs:
  rerender:
    name: Rerender
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/wo